# Generated by Django 3.2.9 on 2021-12-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50)),
                ('title2', models.CharField(max_length=50)),
                ('discribtion', models.CharField(max_length=200)),
            ],
        ),
    ]
