# Generated by Django 3.2.9 on 2021-11-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0002_auto_20211129_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.TextField(default='ali@test.com'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.TextField(default='ali'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.TextField(default='kon'),
        ),
    ]
