# Generated by Django 3.2.9 on 2021-11-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0003_auto_20211129_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.TextField(default=''),
        ),
    ]
