# Generated by Django 3.2.9 on 2021-11-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0007_auto_20211129_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
