# Generated by Django 3.2.9 on 2021-11-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0009_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.DecimalField(decimal_places=0, max_digits=2)),
                ('js', models.DecimalField(decimal_places=0, max_digits=2)),
                ('css', models.DecimalField(decimal_places=0, max_digits=2)),
                ('react', models.DecimalField(decimal_places=0, max_digits=2)),
                ('python', models.DecimalField(decimal_places=0, max_digits=2)),
                ('django', models.DecimalField(decimal_places=0, max_digits=2)),
                ('ps', models.DecimalField(decimal_places=0, max_digits=2)),
                ('bootstrap', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
