# Generated by Django 3.2.9 on 2021-11-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0011_auto_20211130_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='bootstrap',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='css',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='django',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='js',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='ps',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='python',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='react',
        ),
    ]
