# Generated by Django 3.2.9 on 2021-11-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0012_auto_20211130_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='bootstrap',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='css',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='django',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='js',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='ps',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='python',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='react',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
